CMakeLists.txt - require libquotient v0.9.2 or above
Linking fails with distro provided libquotient v0.9.0 I (see below).
Links ok with self-built libquotient v0.9.2

```
/data/KDE/src/kde/network/neochat/src/models/messagecontentmodel.cpp:679:(.text+0x4f32): undefined reference to `_ZNK8Quotient16RoomMessageEvent3hasITkSt12derived_fromINS_12EventContent4BaseEENS3_15UrlBasedContentINS3_8FileInfoEEEEEbv'
/usr/bin/ld: lib/libneochat.a(messagemodel.cpp.o): in function `MessageModel::data(QModelIndex const&, int) const':
/data/KDE/src/kde/network/neochat/src/models/messagemodel.cpp:195:(.text+0x1a96): undefined reference to `_ZNK8Quotient16RoomMessageEvent3hasITkSt12derived_fromINS_12EventContent4BaseEENS3_15UrlBasedContentINS3_8FileInfoEEEEEbv'
/usr/bin/ld: /data/KDE/src/kde/network/neochat/src/models/messagemodel.cpp:195:(.text+0x1aa6): undefined reference to `_ZNK8Quotient16RoomMessageEvent3hasITkSt12derived_fromINS_12EventContent4BaseEENS3_15UrlBasedContentINS3_9ImageInfoEEEEEbv'
/usr/bin/ld: /data/KDE/src/kde/network/neochat/src/models/messagemodel.cpp:195:(.text+0x1ab6): undefined reference to `_ZNK8Quotient16RoomMessageEvent3hasITkSt12derived_fromINS_12EventContent4BaseEENS3_15PlayableContentINS3_9ImageInfoEEEEEbv'
/usr/bin/ld: /data/KDE/src/kde/network/neochat/src/models/messagemodel.cpp:196:(.text+0x1ac6): undefined reference to `_ZNK8Quotient16RoomMessageEvent3hasITkSt12derived_fromINS_12EventContent4BaseEENS3_15PlayableContentINS3_8FileInfoEEEEEbv'
clang++: error: linker command failed with exit code 1 (use -v to see
invocation)
```