Fix undefined reference to webShortcutModel
This was incorrectly capitalized, so I just went ahead and properly
capitalized it so we stop making this mistake!

(cherry picked from commit 80923a2025157fcf8232a25a8e2d33777799e63a)